version = 1

exclude_patterns = [
  "**/*_test.go",
  "**/test/**",
  "**/tests/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/shijl0925/gin-ninja"

[[test_coverage]]
name = "go"
enabled = true
report_file = "coverage.out"
