package ninja

import (
	"fmt"
	"net/http"
	"path"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
)

// VersionConfig configures a named API version namespace.
type VersionConfig struct {
	Prefix      string
	Description string
	// Deprecated marks the API version as deprecated.  Requests to deprecated
	// routes receive a `Deprecation: true` response header (and a date-formatted
	// `Deprecation` header when DeprecatedSince is set).
	Deprecated bool
	// DeprecatedSince is the optional RFC 1123 date at which deprecation was
	// announced.  When set, the `Deprecation` header is emitted as an HTTP-date
	// (e.g. "Mon, 01 Jan 2024 00:00:00 GMT") instead of the literal "true".
	DeprecatedSince time.Time
	// Sunset is a backward-compatible RFC 1123 date string indicating when the
	// version will be removed (e.g. "Mon, 01 Jul 2025 00:00:00 GMT").  Prefer
	// SunsetTime for new code.  When set, the `Sunset` response header is
	// emitted.
	Sunset string
	// SunsetTime is the preferred structured form of Sunset.  If non-zero it
	// takes precedence over the compatibility Sunset string and is formatted as
	// an HTTP-date.
	SunsetTime time.Time
	// MigrationURL is a URL pointing to migration documentation.  When set,
	// a `Link: <url>; rel="deprecation"` header is emitted.
	MigrationURL string
	// sunsetHeaderValue caches the normalized header string derived from
	// SunsetTime or the backward-compatible Sunset field.
	sunsetHeaderValue string
}

func normalizeVersionConfig(name string, cfg VersionConfig) VersionConfig {
	if cfg.Prefix == "" {
		cfg.Prefix = "/" + strings.TrimPrefix(name, "/")
	}
	if !strings.HasPrefix(cfg.Prefix, "/") {
		cfg.Prefix = "/" + cfg.Prefix
	}
	cfg = normalizeVersionSunset(cfg)
	return cfg
}

func normalizeVersionSunset(cfg VersionConfig) VersionConfig {
	if !cfg.SunsetTime.IsZero() {
		cfg.SunsetTime = cfg.SunsetTime.UTC()
		cfg.sunsetHeaderValue = cfg.SunsetTime.Format(http.TimeFormat)
		return cfg
	}
	if cfg.Sunset != "" {
		cfg.sunsetHeaderValue = cfg.Sunset
		if parsed, err := time.Parse(time.RFC1123, cfg.Sunset); err == nil {
			cfg.SunsetTime = parsed.UTC()
		}
	}
	return cfg
}

// normalizedSunsetHeaderValue tolerates raw VersionConfig values that did not
// pass through normalizeVersionConfig yet (for example direct middleware or
// OpenAPI helper tests).
func (cfg VersionConfig) normalizedSunsetHeaderValue() string {
	if cfg.sunsetHeaderValue != "" {
		return cfg.sunsetHeaderValue
	}
	return normalizeVersionSunset(cfg).sunsetHeaderValue
}

func versionSpecConfig(base Config, name string, version VersionConfig) Config {
	cfg := base
	cfg.Version = name
	cfg.Description = joinDescription(base.Description, version.Description)
	if cfg.Title != "" {
		cfg.Title = fmt.Sprintf("%s (%s)", cfg.Title, name)
	}
	return cfg
}

func versionedDocsPattern(base string) string {
	if base == "" {
		return ""
	}
	return path.Join(strings.TrimSuffix(base, "/"), ":version")
}

func versionedDocsPath(base, version string) string {
	if base == "" {
		return ""
	}
	return path.Join(strings.TrimSuffix(base, "/"), version)
}

func versionedOpenAPIPattern(base string) string {
	if base == "" {
		return ""
	}
	root, ext := splitPathExt(base)
	return path.Join(root, ":version") + ext
}

func versionedOpenAPIPath(base, version string) string {
	if base == "" {
		return ""
	}
	root, ext := splitPathExt(base)
	return path.Join(root, version) + ext
}

func splitPathExt(value string) (string, string) {
	if idx := strings.LastIndex(value, "."); idx > strings.LastIndex(value, "/") {
		return value[:idx], value[idx:]
	}
	return strings.TrimSuffix(value, "/"), ""
}

func normalizeVersionParam(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return value
	}
	if idx := strings.IndexByte(value, '.'); idx >= 0 {
		return value[:idx]
	}
	return value
}

func requestVersion(c *gin.Context) string {
	if c == nil {
		return ""
	}
	// The OpenAPI versioned route pattern is /openapi/:version.json (generated by
	// versionedOpenAPIPattern). Gin registers the full "version.json" string as the
	// parameter key, so c.Param("version") returns "" for that route; only the
	// explicit ".json" key works. The Docs route uses /:version without a suffix,
	// so c.Param("version") does match there and the second branch is not reached.
	if value := normalizeVersionParam(c.Param("version")); value != "" {
		return value
	}
	return normalizeVersionParam(c.Param("version.json"))
}

func joinDescription(parts ...string) string {
	values := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part != "" {
			values = append(values, part)
		}
	}
	return strings.Join(values, "\n\n")
}

func versionDeprecationMiddleware(cfg VersionConfig) gin.HandlerFunc {
	// The middleware is also used directly in tests and by package consumers,
	// so normalize sunset compatibility fields here instead of assuming callers
	// always came through lookupVersion/normalizeVersionConfig.
	cfg = normalizeVersionSunset(cfg)
	return func(c *gin.Context) {
		if cfg.Deprecated {
			// Emit the Deprecation header.  Use an HTTP-date when DeprecatedSince
			// is set (RFC 8594), otherwise fall back to the boolean "true".
			if !cfg.DeprecatedSince.IsZero() {
				c.Header("Deprecation", cfg.DeprecatedSince.UTC().Format(http.TimeFormat))
			} else {
				c.Header("Deprecation", "true")
			}

			// Emit the normalized Sunset header value.
			sunsetValue := cfg.normalizedSunsetHeaderValue()
			if sunsetValue != "" {
				c.Header("Sunset", sunsetValue)
			}

			if cfg.MigrationURL != "" {
				c.Header("Link", fmt.Sprintf(`<%s>; rel="deprecation"`, cfg.MigrationURL))
			}
		}
		c.Next()
	}
}

func versionNotFound(c *gin.Context) {
	c.JSON(http.StatusNotFound, map[string]string{"message": "API version not found"})
}
